### ISSUE TITLE
Speical variable for *room-id* vs. multiple `handle-event` generic functions?

### ISSUE THREAD

**Issue by thegoofist** [thegoofist/granolin#1]
In order to support events with type `m.direct`, i defined a new JSON wrapper called `account-data-event`.  Because `m.direct` events are `account_data` events, they are not associated with any particular room. So I altered the calling interface of the `handle-event` generic function from 

    (defgeneric handle-event (client room-id event) ...)

to 

    (defgeneric handle-event (client event &optional room-id) ...)

and updated the project to reflect that change.   This might be fine. One downside, however, is that the new call interface requires that  method implementations of `handle-event` that are specialized on `account-data-event` types will have a useless dangling `&optional room-id` in their `defmethod` forms. 

    (defmethod handle-event ((client my-rad-bot) (ev account-data-event) &optional just-nothing) ...)

An alternative would be to remove `room-id` information from the handler function's call interface altogether, and instead opt to assign the room id's to a special dynamic variable `*room-id*` whenever it is appropriate to do so.  Handler method implementors would then have access to `*room-id*` and it would have the correct value for the event being handled, or would be nil if the event is not a room state nor timeline/message event.  For example:

``` lisp 

(defmethod handle-event :after ((cli echo-bot) (ev text-message-event)) 
    (send-text-message cli *room-id* (msg-body ev)))

``` 

Another alternative would be to define a second event handler generic, something like

    (defgeneric handle-account-event (client event) ...)

or whatever.  I disfavor this approach only b/c one is already specializing on the `account-data-event` when implementing a method for that generic function.  E.g. 

     (defmethod handle-account-event ((client my-bot-plugin) (event account-data-event)) ...)

feels redundant.

So the options are

1. It can be left as-is, i.e. with the sometimes useless optional `room-id` argument
2. Can be changed so that the room id is available to handlers in the global dynamic `*room-id*`
3. Create a second event handling generic function for events that don't have rooms

**Comment by gcentauri** [comment]
I'm leaning toward the *room-id* global. Since this is a specialized client for bots, it seems to make sense to me.  I like the idea that while I'm trying to implement a handler i could have a list of special variables that i can refer to, that "just behave". my main question is how does it change the architecture to make sure these variables just behave?  it seems like there's already a pattern set up for that with the dynamic response variables.

**Comment by thegoofist** [comment]
A revision would be relatively easy. the `handle-event` generic would be drop the `&optional event-id`, and each `defmethod handle-event` that made use of that optional argument would change its use to `*event-id*`.  

The architecture wouldn't have to change at all.  Since granolin is single-threaded, it only ever processes one event at a time, hence setting the special variable *event-id* at the same time as the event special variables is a safe thing to do.  

If a particular bot needs access to event id at a later time, they will have to define state to save them for later.
